const mongoose = require("mongoose");

const carSchema = new mongoose.Schema({
  urunAdi: { type: String, alias: "Ürün Adı" },
  hasarBilgisi: { type: String, alias: "Hasar Bilgisi" },
  saticiBilgileri: { type: String, alias: "Satıcı Bilgileri" },
  aciklama: { type: String, alias: "Açıklama" },
  telefonNumarasi: { type: String, alias: "Telefon Numarası" },
  fiyat: { type: String, alias: "Fiyat" },
  ilanNo: { type: String, alias: "İlan No" },
  ilanTarihi: { type: String, alias: "İlan Tarihi" },
  marka: { type: String, alias: "Marka" },
  seri: { type: String, alias: "Seri" },
  model: { type: String, alias: "Model" },
  yil: { type: String, alias: "Yıl" },
  kilometre: { type: String, alias: "Kilometre" },
  vitesTipi: { type: String, alias: "Vites Tipi" },
  yakitTipi: { type: String, alias: "Yakıt Tipi" },
  kasaTipi: { type: String, alias: "Kasa Tipi" },
  renk: { type: String, alias: "Renk" },
  motorHacmi: { type: String, alias: "Motor Hacmi" },
  motorGucu: { type: String, alias: "Motor Gücü" },
  cekis: { type: String, alias: "Çekiş" },
  aracDurumu: { type: String, alias: "Araç Durumu" },
  ortYakitTuketimi: { type: String, alias: "Ort. Yakıt Tüketimi" },
  yakitDeposu: { type: String, alias: "Yakıt Deposu" },
  boyaDegisen: { type: String, alias: "Boya-değişen" },
  takasaUygun: { type: String, alias: "Takasa Uygun" },
  kimden: { type: String, alias: "Kimden" },
  uretimYili: { type: String, alias: "Üretim Yılı (İlk/Son)" },
  garantiDurumu: { type: String, alias: "Garanti Durumu" },
  aracTuru: { type: String, alias: "Araç Türü" },
  ilkSahip: { type: String, alias: "Aracın ilk sahibiyim" },
  sinifi: { type: String, alias: "Sınıfı" },
  plakaUyruğu: { type: String, alias: "Plaka Uyruğu" },
  yillikMTV: { type: String, alias: "Yıllık MTV" },
  sanziman: { type: String, alias: "Şanzıman" },
  ortalamaKasko: { type: String, alias: "Ortalama Kasko" },
  ortalamaTrafikSigortasi: { type: String, alias: "Ortalama Trafik Sigortası" },
  silindirSayisi: { type: String, alias: "Silindir Sayısı" },
  tork: { type: String, alias: "Tork" },
  hizlanma: { type: String, alias: "Hızlanma (0-100)" },
  maksimumHiz: { type: String, alias: "Maksimum Hız" },
  sehirIciTuketim: { type: String, alias: "Şehir İçi Yakıt Tüketimi" },
  sehirDisiTuketim: { type: String, alias: "Şehir Dışı Yakıt Tüketimi" },
  uzunluk: { type: String, alias: "Uzunluk" },
  genislik: { type: String, alias: "Genişlik" },
  yukseklik: { type: String, alias: "Yükseklik" },
  agirlik: { type: String, alias: "Ağırlık" },
  bosAgirlik: { type: String, alias: "Boş Ağırlığı" },
  koltukSayisi: { type: String, alias: "Koltuk Sayısı" },
  bagajHacmi: { type: String, alias: "Bagaj Hacmi" },
  onLastik: { type: String, alias: "Ön Lastik" },
  aksAraligi: { type: String, alias: "Aks Aralığı" },
  resimURL: { type: String, alias: "Resim URL" },
  adres: { type: String, alias: "Adres" },
});

module.exports = mongoose.model("Car", carSchema, "car_listings");
